# Generated by Django 3.1.5 on 2021-01-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='state',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
