# Generated by Django 3.1.5 on 2021-01-26 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210126_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='http_verb',
            field=models.CharField(choices=[('POST', 'POST'), ('GET', 'GET'), ('HEAD', 'HEAD'), ('PUT', 'PUT'), ('DELETE', 'DELETE'), ('CONNECT', 'CONNECT'), ('OPTIONS', 'OPTIONS'), ('TRACE', 'TRACE'), ('PATCH', 'PATCH')], default='GET', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='requests',
            name='respnse',
            field=models.TextField(null=True),
        ),
    ]
