# Generated by Django 3.1.5 on 2021-01-27 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210126_2329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requests',
            old_name='respnse',
            new_name='response',
        ),
    ]
